- build.gradle
- src/main/kotlin/com/tschuchort/compiletesting/KotlinCompilation.kt
- src/test/kotlin/com/tschuchort/compiletesting/KotlinCompilationTests.kt
Please, this _pull request_ adds the ability to provide `pluginClasspaths` for the compilation.
Thanks in advance!
> Add pluginClasspaths to the configuration

- src/main/kotlin/com/tschuchort/compiletesting/KotlinCompilation.kt
Small change to be able to test with Kotlin EAP versions like `1.3.60-eap-143`.
> Regex: consideration of other details after major.minor.patch versions

- README.md
- build.gradle
- gradle.properties
- src/main/kotlin/com/tschuchort/compiletesting/KotlinCompilation.kt
- src/test/kotlin/com/tschuchort/compiletesting/KotlinCompilationTests.kt
This adds support for Kotlin 1.3.70. The major change was a breaking API in IncrementalProcessor that needed an additional logger passed in. The logger used is also used in the kotlin lang tests for kapt. However, an alternative would be to implement the interface for KaptLogger within the project. This *seems* fine though.
Compiles and tests successfully.
Resolves #38
> Bump to Kotlin 1.3.70

- src/main/kotlin/com/tschuchort/compiletesting/JavacUtils.kt
- src/test/kotlin/com/tschuchort/compiletesting/JavacUtilsTest.kt
****Reason****
Our CI build server happen to return `Picked up JAVA_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
javac 1.8.0_222` for `javac -version`, which `matchEntire` doesn't match.
Let me know if I should add tests :)
> Replacing matchEntire with find in Regex

- src/main/kotlin/com/tschuchort/compiletesting/KotlinCompilation.kt
The Regex used to match kotlin runtime libraries required
version to have 3 numbers which broke with 1.4 milestore
releases since they have versions like 1.4-M1.
This PR updates the regex to make the PATCH version optional.
Since the regex was mostly duplicated, I moved it to a helper.
> Fix regex to support kotlin 1.4

- ksp/build.gradle
- ksp/gradle.properties
This PR adds an ARTIFACT_ID to the KSP module so that it won't use
the same name as the main artifact.
I've also changed it to declare dependency on the main module with
the version name so that the generated POM does have the version.
> Setup publishing for the KSP artifact

- ksp/build.gradle
- ksp/src/main/kotlin/com/tschuchort/compiletesting/Ksp.kt
- ksp/src/test/kotlin/com/tschuchort/compiletesting/AbstractTestSymbolProcessor.kt
- ksp/src/test/kotlin/com/tschuchort/compiletesting/KspTest.kt
There are 2 breaking changes with [20200731](https://github.com/android/kotlin/releases/tag/1.4.0-rc-dev-experimental-20200731) release:
* Output directory was reorganized to be more complying with Gradle convention.
* Added a logger for KSP processors.
For the logger, in current model for KSP tests, it looks to be not easy to obtain the same output stream as KotlinCompilation, therefore using System.err and left a TODO.
> support ksp 20200731 release

- ksp/src/main/kotlin/com/tschuchort/compiletesting/Ksp.kt
- ksp/src/test/kotlin/com/tschuchort/compiletesting/KspTest.kt
Incremental mode is disabled by default in the new KSP version, this adds corresponding options to configure them in tests
> Add options for enabling incremental and incremental logging

- ksp/src/main/kotlin/com/tschuchort/compiletesting/Ksp.kt
This tripped me up on some testing locally due to it not being the conventional `resources` name
> Fix name for resources dir

- ksp/build.gradle
- ksp/src/main/kotlin/com/tschuchort/compiletesting/Ksp.kt
- ksp/src/test/kotlin/com/tschuchort/compiletesting/KspTest.kt
This PR fixes a bug where we were not reporting java sources when building ksp arguments. 
Failing to add them means `getSymbolsAnnotatedWith` misses all java sources.
I've also updated KSP to `1.4.20-dev-experimental-20210111`
> Report java sources to KSP

- core/src/main/kotlin/com/tschuchort/compiletesting/AbstractKotlinCompilation.kt
- core/src/main/kotlin/com/tschuchort/compiletesting/HostEnvironment.kt
- core/src/main/kotlin/com/tschuchort/compiletesting/KotlinCompilation.kt
- core/src/main/kotlin/com/tschuchort/compiletesting/KotlinJsCompilation.kt
This PR adds caching for host classpath to avoid calling ClassGraph for
every compilation. In my local tests, it saves between 50 to 80ms per
compilation on my laptop, which is not necessarily much but adds up when
you run hundreds of them.
I've also cached common jars we find from there. It does not necessarily
help with performance but rather as a cleanup to keep all of them in 1
place.
Test: existing tests
Issue: #113
> Cache host classpath

- README.md
- build.gradle
- ksp/build.gradle
- ksp/src/main/kotlin/com/tschuchort/compiletesting/Ksp.kt
- ksp/src/test/kotlin/com/tschuchort/compiletesting/AbstractTestSymbolProcessor.kt
- ksp/src/test/kotlin/com/tschuchort/compiletesting/KspTest.kt
This includes some fixes to tests that would otherwise end up in an infinite loop with its new multiple rounds behavior.
> Update KSP to 1.4.30-1.0.0-alpha02 and Kotlin to 1.4.30

- core/src/main/kotlin/com/tschuchort/compiletesting/KotlinCompilation.kt
That flag needs to be set to true with Kotlin 1.5.0 in order to use the old backend. The `useIr` property became a no-op.
See also: https://github.com/JetBrains/kotlin/blob/1.5.0-M1/compiler/cli/src/org/jetbrains/kotlin/cli/jvm/jvmArguments.kt#L195-L200
> Expose a property that allows to enable the old JVM backend.

- ksp/build.gradle
- ksp/src/main/kotlin/com/tschuchort/compiletesting/Ksp.kt
- ksp/src/test/kotlin/com/tschuchort/compiletesting/AbstractTestSymbolProcessor.kt
- ksp/src/test/kotlin/com/tschuchort/compiletesting/KspTest.kt
KSP alpha08 introduces a new `SymbolProcessorProvider` API to allow for creating immutable/stateless processors. This updates the KSP APIs to this new pattern, as the old `init()`-based pattern is deprecated and will eventually be removed.
> Update KSP to alpha08 and adopt new ProcessorProvider API

- build.gradle
Kotlin 1.5 now targets JVM 1.8 [by defaut](https://kotlinlang.org/docs/whatsnew15.html#new-default-jvm-target-1-8), so there's no need to specify it again explicitly.
> Remove explicit jvmTarget specification

- README.md
illegal-access argument will not work in JDK 17 or higher and result in an error, this also adds missing `parser` and `code` subpackages
> Fix JDK 16+ recommendations

- .github/workflows/ci.yml
https://github.blog/changelog/2021-08-30-github-actions-setup-java-now-supports-dependency-caching/
> setup-java v2 cache parameter

- core/src/main/kotlin/com/tschuchort/compiletesting/KotlinCompilation.kt
- core/src/test/kotlin/com/tschuchort/compiletesting/KotlinCompilationTests.kt
> Include the classpaths in the Result.classLoader to be able to load classes from dependencies.

- README.md
- build.gradle
- gradle.properties
- ksp/build.gradle
- ksp/src/main/kotlin/com/tschuchort/compiletesting/Ksp.kt
Resolves #222 along the way and adds support for KSP's new `allWarningsAsError` mode
> Update to Kotlin 1.6 and KSP 1.0.1

- ksp/src/main/kotlin/com/tschuchort/compiletesting/Ksp.kt
> Add 'withCompilation' to enable full compilation with symbol processors. 

- core/src/main/kotlin/com/tschuchort/compiletesting/KotlinCompilation.kt
This API is actually removed in Kotlin 1.6.20 and normally configured via freeCompilerArg. This makes testing Kotlin 1.6.20 easier
> Don't set strictJavaNullabilityAssertions unless requested

- build.gradle
- core/src/main/kotlin/com/tschuchort/compiletesting/AbstractKotlinCompilation.kt
- core/src/main/kotlin/com/tschuchort/compiletesting/MainComponentRegistrar.kt
- core/src/test/kotlin/com/tschuchort/compiletesting/KotlinCompilationTests.kt
> Support K2

- README.md
- build.gradle
- core/src/main/kotlin/com/tschuchort/compiletesting/AbstractKotlinCompilation.kt
- core/src/main/kotlin/com/tschuchort/compiletesting/KotlinCompilation.kt
- core/src/main/kotlin/com/tschuchort/compiletesting/KotlinJsCompilation.kt
- core/src/test/kotlin/com/tschuchort/compiletesting/KotlinJsCompilationTests.kt
- ksp/build.gradle
- ksp/src/main/kotlin/com/tschuchort/compiletesting/Ksp.kt
A follow-up to #380 (and closes #379). 
Let's see if I have better luck with Windows tests.
> Support Kotlin 1.9.0
